create test framework for TestRail API
olgayuks/TestRailApiTests pull request #1
Opened 2021-04-18 18:28 UTC by olgayuks

2021-04-19 07:26 UTC, Maria-Dolia requested changes
Исправить нейминг по тестам и пингануть меня

2021-04-19 07:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/Assertion/ProjectAssertion.cs
> +            actual.Url.Should().EndWith(actual.Id.ToString());
можно еще проверить, что начинается с урла нашей прилаги )

2021-04-19 07:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/Factories/ResponseFactory.cs
> +        public static SuiteResponse GetSuiteResponse(CreateSuiteModel createSuiteModel)
лучше назвать `SuiteResponseModel`, ато немного вводит в заблуждение

2021-04-19 07:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/Mocks/ProjectMocks.cs
> +            var missingNameMessage = "Field :name is a required field.";
Давай вынесем в константы сообщения об ошибках)

2021-04-19 07:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/Services/ProjectService.cs
> +            return _client.GetAsync("index.php?/api/v2/get_project/" + projectId);
а чего не через $?

2021-04-19 07:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/Tests/ProjectTests.cs
> +        [AllureXunit(DisplayName = "POST index.php?/api/v2/add_project when returns 200")]
вы что копируете дескрипшены друг у друга?))
when что?

2021-04-19 07:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/Tests/ProjectTests.cs
> +    }
стоит разбить тесты 
Tests
> DeleteProjectTests
> AddProjectTests
> ...

2021-04-19 14:32 UTC, ohthatbaguk commented on TestRailApiTestFramework/Tests/AddProjectTests.cs
> +}
можно добавить тест на проверку поля, когда значение выходит за допустимые размеры
и в проектах и сьютах

2021-04-20 09:43 UTC, ohthatbaguk approved these changes

2021-04-20 10:26 UTC, Maria-Dolia requested changes

2021-04-20 10:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/Assertion/ProjectAssertion.cs
> +            _config = new ConfigurationBuilder().AddJsonFile("appsettings.json").Build();
считывай конфиги где-нибудь типа в стартапе один раз , а тут у тебя будет просто вызов статики
А то в каждом месте , где нужны конфиги, читать файлик - ну такое

2021-04-20 10:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/Assertion/ProjectAssertion.cs
> +            actual.SuiteMode.Should().Be(3);
меджик намберс
сделай коснтанту с красивым названием, чтобы было понятно ткуда эта тройка взялсь вообще

2021-04-20 10:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/Constants/ConstantsForNotes.cs
> +    public class ConstantsForNotes
NotesValidationConstants would be better

2021-04-20 10:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/Extension/HttpClientExtensions.cs
> +        public static async Task<T> ReadAsJsonAsync<T>(this HttpContent content)
это скорее десириализация, чем Read As Json

2021-04-20 10:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/Extension/HttpClientExtensions.cs
> +                "application/json"
"application/json" в константс контент тайпс

2021-04-20 10:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/Factories/ProjectFactory.cs
> +            };
почему вы не используете Rules как в доках Bogus описано? =(

2021-04-20 10:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/Mocks/ProjectMocks.cs
> +            var incorrectId = 1;
Разве 1 - это инкаррект айди?
по-моему айдиха проекта как раз таки интовая

2021-04-20 10:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/Extension/HttpClientExtensions.cs
> +    }
мб лучше метод выше как то подправить, чем определять новый?

2021-04-20 10:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/Steps/ProjectSteps.cs
> +            response.StatusCode.Should().Be(HttpStatusCode.OK);
кстати вот тут можно добавлять какой нибудь ерор мессидж, чтобы если степ свалился, ты разу понимала, что это проиизошло на моменте создания проекта)
А то будет вот так 
![image](https://user-images.githubusercontent.com/65294126/115377678-8289aa00-a1d8-11eb-9659-5194b86be982.png)

2021-04-20 10:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/Tests/AddProjectTests.cs
> +        public async Task CreateProjectWhenUnAuthorized_ShouldReturnUnauthorized()
`CreateProject_WhenUnAuthorized_ShouldReturnUnauthorized`

2021-04-20 10:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/Tests/AddProjectTests.cs
> +    }
можно сделать одним тестом

2021-04-20 10:26 UTC, Maria-Dolia commented on TestRailApiTestFramework/appsettings.json
> +}
посмотри как мы с Наташей красиво конфиг файл сделали, этот варик максимально приближен к реальному проекту)

2021-04-23 06:42 UTC, Maria-Dolia commented on TestRailApiTestFramework/Tests/DeleteProjectTests.cs
> +            // //Assert
// лишние

2021-04-23 06:42 UTC, Maria-Dolia commented on TestRailApiTestFramework/Tests/BaseTest.cs
>          }
можем вынесити в какие нить `HttpClientExtentions`?

2021-04-23 06:42 UTC, Maria-Dolia commented on TestRail/Tests/Projects/GetProjectTests.cs
> +            ProjectAssertion.AssertProject(createdProject, responseProject);
а где проверка респонс статус кода?

2021-04-23 06:42 UTC, Maria-Dolia commented on TestRail/Tests/Suites/AddSuiteTests.cs
> +            response.ResponseStatusCode(HttpStatusCode.BadRequest, "Expected BadRequest status.");
а тут нет ероров?

2021-04-23 06:42 UTC, Maria-Dolia commented on TestRail/Tests/Suites/UpdateSuiteTests.cs
> +            var expectedSuite = ResponseFactory.SuiteResponseModel(suiteModel);
это должно быть в Arrange

2021-04-28 07:11 UTC, merged